articles/urls.py
from django.urls import path, include  # 반드시 추가해줘야 함
from . import views  # 같은 articles 내 view 를 가져옴


# /articles/ ____ , 사용자는 이미 articles 까지 들어온 상태
app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),

    # path('new/', views.new, name='new'),  # views 의 new함수, new.html 생성 필요
    
    path('create/', views.create, name='create'),
    # /articles/4/delete/
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    # /articles/3/comments/
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    # /articles/3/comments/2/delete/
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include  # include 반드시 선언 필요

from django.conf import settings
from django.conf.urls.static import static

# 사용자가 가장 먼저 들어오는 entry point
urlpatterns = [
    
    # 다음 step => articles 에 urls.py 생성
    # /jobs/ 로 들어왔다면 jobs/urls.py 로 이동하도록 설정
    path('jobs/', include('jobs.urls')),

    # /articles/ 로 들어왔다면 articles/urls.py 로 이동하도록 설정
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]


# 사용자가 Media 파일이 있는 곳으로 올 수 있는 경로를 추가한다.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path, include  # 반드시 추가해줘야 함
from . import views  # 같은 jobs 내 view 를 가져옴


# /jobs/ ____ , 사용자는 이미 jobs 까지 들어온 상태
app_name = 'jobs'
urlpatterns = [
    path('', views.insert, name='insert'),
    path('past_job/', views.past_job, name='past_job'),
    path('delete/', views.delete, name='delete')
]

articles/models.py
from django.db import models
from imagekit.processors import Thumbnail
from imagekit.models import ImageSpecField

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField() # 문자열 빈 값 저장은 null 이 아니라 '' 그 외 다른 것들은 ''과 null 둘 다 가능
    # blank: 데이터 유효성과 관련되어 있다.
    # null: DB와 관련되어 있다.
    # '', Null?
    image = models.ImageField(blank=True)
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(200, 200)],
        format='JPEG',
        options={'quality': 90},

    )
    created_at = models.DateTimeField(auto_now_add=True) # 추가할 때 현재시간을 기록하겠다??
    updated_at = models.DateTimeField(auto_now=True) # 언제든지 자동으로 현재시간을 기록하겠다.
    
# $python manage.py makemigrations  => django한테 model을 만든 사항을 알려줌 0001_initial 이 만들어짐
# $python manage.py migrate  => migrations 적용
# 다음 step crud/urls.py setting

class Comment(models.Model):
    # on_delete=models.CASCADE == 'Article 이 삭제되면 Comment 도 함께 삭제'
    # related_name == 'Article instance 가 comment 를 역참조 할 수 있는 이름을 정의'
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)  # 추가 됐을때만
    updated_at = models.DateTimeField(auto_now=True)  # 항상

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.content

jobs/models.py
from django.db import models

class Job(models.Model):
    Name = models.CharField(max_length=20)
    past_job = models.TextField()
    profile_image = models.ImageField(blank=True)

    def __str__(self):
        return self.name

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .models import Comment

# templates 폴더 생성 => templates가 중복되지 않도록 templates 내에 articles 폴더 추가로 생성

# articles 의 메인 페이지, article list 를 보여줌
def index(request):
    # article 내에 모든 data를 받아오겠다.
    # SELECT * FROM 과 동일한 문구(SQLite3))
    articles = Article.objects.all()  
    context = {'articles': articles}
    # 순서 중요, 세번째는 무엇을 넘겨줄지가 들어갸아한다. 
    return render(request, 'articles/index.html', context)


# Variable Routing 으로 사용자가 보기를 원하는 페이지 pk 를 받아서
# Detail 페이지를 보여준다.
def detail(request, article_pk):
    # SELECT * FROM article WHERE pk=
    article = get_object_or_404(Article, pk=article_pk)

    comments = article.comments.all()

    context = {
        'article': article,
        'comments': comments,
        }
    
    return render(request, 'articles/detail.html', context)


# 입력 페이지 제공
# GET/ articles/create/
# def new(request):
#     return render(request, 'articles/new.html')


# 데이터를 전달 받아서 article 생성
# POST /articles/create/
def create(request):

    # 만약 POST 일 경우 사용자 데이터 받아서 article 생성
    if request.method == 'POST':
        # new 가 전달한 data들을 받기
        title = request.POST.get('title')  # GET에서 POST로 변경
        content = request.POST.get('content')
        image = request.FILES.get('image')
        # 인스턴스 생성
        article = Article(title = title, content=content, image= image)

        article.title = title
        article.content = content
        article.save()

        # <a href="/articles/">와 같은 역할 => redirect import해줘야함


        return redirect('articles:detail', article.pk)
    
    # 만약 GET 요청으로 들어오면 html 페이지 rendering
    else:
        return render(request, 'articles/create.html')


# 사용자로부터 받은 article_pk 값에 해당하는 데이터 삭제
def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        article.delete()

        return redirect('articles:index')
    else:
        return redirect('articles:detail', article_pk)


# /articles/5/update/
def update(request, article_pk):
    # POST /articles/5/update/ : 실제 Update 로직이 수행
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')

        if image:
            article.image = image

        article.title = title
        article.content = content
        article.save()
        return redirect('articles:detail', article.pk)

    # GET /articles/5/update/ : Update 를 하기위한 Form 을 제공하는 페이지
    else:
        context = {'article': article}
        return render(request, 'articles/update.html', context)

def comments_create(request, article_pk):
    # article_pk 에 해당하는 article 에 새로운 comment 생성
    # 생성한 다음 article detail page 로 redirect
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        content = request.POST.get('content')
        comment = Comment()
        comment.content = content
        comment.article = article
        # comment.article_id = article_pk
        comment.save()
        
    return redirect('articles:detail', article_pk)


def comments_delete(request, article_pk, comment_pk):
    # POST 요청으로 들어왔다면
    if request.method == 'POST':
        # comment_pk 에 해당하는 댓글 삭제
        comment = get_object_or_404(Comment, pk=comment_pk)
        comment.delete()

    # detail 페이지로 이동
    return redirect('articles:detail', article_pk)

jobs/views.py
from django.shortcuts import render, redirect
from .models import Job
from faker import Faker
fake = Faker()

def insert(request):
    return render(request, 'jobs/insert.html')

# GIF_API = f'https://api.giphy.com/v1/gifs/search?api_key=yffLcxywQ73zcI0YssOgH5IvPpi9qCU1&q={ p_j }&limit=1&offset=0&rating=G&lang=en'


def past_job(request):
    jobs = Job.objects.all()
    name = request.POST.get('Name')
    image = request.FILES.get('image')
    if jobs.filter(Name=name):

        job = Job.objects.get(Name=name)
    else:
        pastjob = fake.job()
        job = Job()
        job.profile_image = image
        job.Name = name
        job.past_job = pastjob
        job.save()


# https://api.giphy.com/v1/gifs/search?api_key=yffLcxywQ73zcI0YssOgH5IvPpi9qCU1&q=??&limit=1&offset=0&rating=G&lang=en

    context = {'job': job}
    return render(request, 'jobs/past_job.html', context)

def delete(request):
    job = Job.objects.all()
    if request.method == 'POST':
        job.delete()

        return redirect('jobs:insert')
    else:
        return redirect('jobs:insert')

articles/templates/articles/create.html
{% extends 'base.html' %}
{% block title %}New Article{% endblock title %}

{% block body %}
  <h1>New Article</h1>
  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data"> <br>
    {% comment %} 해킹에 대해 자유롭다는 것을 보장하기 위해 {% endcomment %}
    {% csrf_token %}  

    <input type="text" name="title"> <br>
    <textarea name="content" cols="30" rows="10"></textarea><br>
    <label for="image">이미지</label>
    <input type="file" name="image" id="image" accept="image/*"><br>
    <button type="submit">생성하기</button>
  </form>
{% endblock body %}

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block title %}Article Detail
{% endblock title %}

{% block body %}
  <h1>{{ article.title }}</h1>
  <p>작성일자: {{ article.created_at }}</p>
  <hr>

  {% if article.image %}
  <img src="{{ article.image.url }}" alt="{{ article.image }}">
  {% endif %}

  <p>{{ article.content }}</p>

  <hr>

  <h4>Comments</h4>
  
  <form action="{% url 'articles:comments_create' article.pk %}" method='POST'>
    {% csrf_token %}
    <input type="text" name='content'>
    
    <button type="submit">댓글 작성</button>
  </form>

  <ul>
  {% for comment in comments %}
    <li>{{ comment.content }}</li>
    
    <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method='POST'>
      {% csrf_token %}
      <button type="submit">삭제하기</button>
    </form>
  {% endfor %}
  </ul>
  

  <hr>
  <a href="{% url 'articles:index' %}">[뒤로가기]</a><br>
  <a href="{% url 'articles:update' article.pk %}">[수정하기]</a>
  <form action="{% url 'articles:delete' article.pk %}" method="POST" onclick="return confirm('Are you sure?')">
    {% csrf_token %}
    <button type="submit">[삭제하기]</button>
  </form>

  {% comment %} <a href="{% url 'articles:delete' article.pk %}" onclick="return confirm('Are you sure?')">[삭제하기]</a> {% endcomment %}
  
{% endblock body %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% comment %} static 파일들을 불러오겠다. {% endcomment %}
{% load static %}

{% block title %}Articles{% endblock title %}
{% block body %}
  <h1>Articles</h1>
  <a href="{% url 'articles:create' %}">[작성하기]</a>
  {% comment %} url 을 생성해주는게 static tag {% endcomment %}
  <img src="{% static 'articles/images/식빵 고양이.jpg' %}" alt="식빵 고양이">
  <hr>
  {% for article in articles %}
    <div>
      {% if article.image %}
        <img src="{{ article.image_thumbnail.url }}" alt="{{ article.image }}">
      {% endif %}
      <h3><a href="{% url 'articles:detail' article.pk %}">{{ article.pk }}. {{ article.title }}</a></h3>
      <p>{{ article.content }}</p>
    </div>
    <br>
  {% endfor %}
{% endblock body %}

articles/templates/articles/update.html
  
{% extends 'base.html' %}

{% block title %}Update Article{% endblock title %}

{% block body %}
<h1>Update Article</h1>
{% if article.image %}
  <img src="{{ article.image.url }}" alt="{{ article.image }}">
{% endif %}
<form action="{% url 'articles:update' article.pk %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="title" value="{{ article.title }}"><br>
  <textarea name="content" cols="30" rows="10">{{ article.content }}</textarea><br>
  <label for="image">이미지</label>
  <input type="file" name="image" id="image"> <br>
  <button type="submit">수정하기</button>
</form>
<a href="{% url 'articles:detail' article.pk%}">[뒤로가기]</a>
{% endblock body %}

crud/templates/base.html
{% comment %} 모든 프로젝트에 적용되게 하기 위해 crud에 만들어줌 {% endcomment %}
{% load static %}


<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'base.css' %}">
  <link rel="shortcut icon" href="{% static 'favicon-96x96.png' %}" type="image/x-icon">
</head>
<body>
  {% block body %}
  {% endblock body %}
</body>
</html>

jobs/templates/jobs/insert.html
{% extends 'base.html' %}
{% block title %}Insert Name
{% endblock title %}

{% block body %}
  <h1>전생직업 확인</h1>
  {% comment %} GET /jobs/ => action이 비어있을 때 {% endcomment %}
  <form action="{% url 'jobs:past_job' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="name">이름을 입력하세요</label><br>
    
    <input type="text" name="Name"><br>
    <input id="image" type="file" name="image" accept="images/*"><br>
    <button type="submit">실행하기</button>
  </form>
  <form action="{% url 'jobs:delete' %}"  method="POST" onclick="return confirm('Are you sure?')">
    {% csrf_token %}
    
    <button type="submit">[삭제하기]</button>
  </form>
{% endblock body %}

jobs/templates/jobs/past_job.html
{% extends 'base.html' %}
{% block title %}Past Job
{% endblock title %}

{% block body %}
<h1>{{ job.Name }}은 전생에 {{ job.past_job }}이었습니다.</h1>
{% if job.profile_image %}
<img src="{{ job.profile_image }}" alt="job.profile_image">
{% endif %}
{% endblock body %}